### ISSUE TITLE
Error on pinItemStyle

### ISSUE THREAD

**Issue by donjerick** [lotosbin/react-native-pin-input-sample#1]
`
ExceptionsManager.js:73 TypeError: In this environment the sources for assign MUST be an object.This error is a performance optimization and not spec compliant.
`
Getting this error whenever I put custom style value for pinItemStyle prop.

Suggestion:
Please use Stylesheet.flatten() to combine styles instead of using {...this.props.pinItemStyle}

**Comment by lotosbin** [comment]
https://github.com/lotosbin/react-native-pin-input/issues/12
